/**
 * Blog cms.ts template
 *
 * Content types: Blog Post, Author, Category
 * Includes typed helpers for programmatic access
 */

export const CMS_BLOG_TEMPLATE = `/**
 * CMS Setup - Blog Template
 *
 * Content types: Blog Post, Author, Category
 * Uses defineContentType() for schema definitions and createTypedHelpers() for typed CRUD access.
 *
 * @example Type-safe queries in Convex functions
 * \`\`\`typescript
 * import { content } from "./cms";
 *
 * const posts = await content.blog.list(ctx, { status: "published" });
 * posts.page[0].data.title;  // string
 * \`\`\`
 *
 * Generated by: npx convex-cms init --template blog
 */

import { defineContentType, createTypedHelpers } from "convex-cms";
import { components } from "./_generated/api";
import { v } from "convex/values";

// =============================================================================
// CONTENT TYPE DEFINITIONS
// =============================================================================

export const blogPost = defineContentType({
  name: "Blog Post",
  validator: v.object({
    title: v.string(),
    slug: v.string(),
    excerpt: v.optional(v.string()),
    content: v.string(),
    featuredImage: v.optional(v.string()),
    publishedAt: v.optional(v.number()),
    author: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    metaTitle: v.optional(v.string()),
    metaDescription: v.optional(v.string()),
  }),
  meta: {
    displayName: "Blog Post",
    titleField: "title",
    slugField: "slug",
    fields: {
      title: { searchable: true, maxLength: 200, placeholder: "Post title" },
      slug: {
        pattern: "^[a-z0-9-]+$",
        patternMessage: "Only lowercase letters, numbers, and hyphens",
        description: "URL-friendly identifier",
      },
      excerpt: { maxLength: 300, placeholder: "Brief summary for listings" },
      content: { renderAs: "richText", searchable: true },
      featuredImage: {
        renderAs: "media",
        allowedMimeTypes: ["image/*"],
        maxFileSize: 5 * 1024 * 1024,
      },
      publishedAt: { renderAs: "datetime" },
      author: { renderAs: "reference", allowedContentTypes: ["author"] },
      tags: { renderAs: "tags", allowCreate: true, maxTags: 10 },
      metaTitle: {
        maxLength: 60,
        placeholder: "SEO title (defaults to post title)",
        description: "Title shown in search results",
      },
      metaDescription: {
        maxLength: 160,
        placeholder: "SEO description",
        description: "Description shown in search results",
      },
    },
  },
});

export const author = defineContentType({
  name: "Author",
  validator: v.object({
    name: v.string(),
    slug: v.string(),
    bio: v.optional(v.string()),
    avatar: v.optional(v.string()),
    email: v.optional(v.string()),
    website: v.optional(v.string()),
  }),
  meta: {
    displayName: "Author",
    titleField: "name",
    slugField: "slug",
    fields: {
      name: { searchable: true, maxLength: 100 },
      slug: {
        pattern: "^[a-z0-9-]+$",
        patternMessage: "Only lowercase letters, numbers, and hyphens",
      },
      bio: { renderAs: "richText" },
      avatar: {
        renderAs: "media",
        allowedMimeTypes: ["image/*"],
        maxFileSize: 2 * 1024 * 1024,
      },
      email: { placeholder: "author@example.com" },
      website: { placeholder: "https://..." },
    },
  },
});

export const category = defineContentType({
  name: "Category",
  validator: v.object({
    name: v.string(),
    slug: v.string(),
    description: v.optional(v.string()),
    color: v.optional(v.string()),
    parentCategory: v.optional(v.string()),
    sortOrder: v.optional(v.number()),
  }),
  meta: {
    displayName: "Category",
    titleField: "name",
    slugField: "slug",
    fields: {
      name: { searchable: true, maxLength: 100 },
      slug: {
        pattern: "^[a-z0-9-]+$",
        patternMessage: "Only lowercase letters, numbers, and hyphens",
      },
      description: { maxLength: 500 },
      color: { placeholder: "#3B82F6", description: "Hex color for UI display" },
      parentCategory: { renderAs: "reference", allowedContentTypes: ["category"] },
      sortOrder: { min: 0, description: "Lower numbers appear first" },
    },
  },
});

// =============================================================================
// TYPED HELPERS
// =============================================================================

export const content = createTypedHelpers(components.cms, {
  blog: blogPost,
  author: author,
  category: category,
});
`;

export const BLOG_SCHEMA_DESCRIPTION = "Blog (post, author, category)";
