/**
 * Blog cms.ts template
 *
 * Content types: Blog Post, Author, Category
 * Includes typed helpers for programmatic access
 */

export const CMS_BLOG_TEMPLATE = `/**
 * CMS Setup - Blog Template
 *
 * This file defines content types and creates typed helpers for type-safe access.
 *
 * Architecture:
 * - defineContentType() creates schema definitions for the admin API
 * - createTypedHelpers() creates type-safe CRUD helpers for programmatic access
 * - Both work together: definitions go to admin API, helpers provide typed access
 *
 * @example Type-safe queries in Convex functions
 * \`\`\`typescript
 * import { content } from "./cms";
 *
 * // Fully typed - data fields have correct types
 * const posts = await content.blog.list(ctx, { status: "published" });
 * posts.page[0].data.title;  // string
 * \`\`\`
 *
 * Generated by: npx convex-cms init --template blog
 */

import { defineContentType, createTypedHelpers } from "convex-cms";
import { components } from "./_generated/api";
import { v } from "convex/values";

// =============================================================================
// CONTENT TYPE DEFINITIONS
// =============================================================================

export const blogPost = defineContentType({
  name: "Blog Post",
  validator: v.object({
    title: v.string(),
    slug: v.string(),
    excerpt: v.optional(v.string()),
    content: v.string(),
    featuredImage: v.optional(v.string()),
    publishedAt: v.optional(v.number()),
    author: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
  }),
  meta: {
    displayName: "Blog Post",
    titleField: "title",
    slugField: "slug",
    fields: {
      title: { label: "Title", maxLength: 200, searchable: true },
      slug: { label: "URL Slug", description: "URL-friendly identifier" },
      excerpt: { label: "Excerpt", maxLength: 300 },
      content: { label: "Content", renderAs: "richText" },
      featuredImage: { label: "Featured Image", renderAs: "media" },
      publishedAt: { label: "Publish Date", renderAs: "datetime" },
      author: { label: "Author" },
      tags: { label: "Tags", renderAs: "tags" },
    },
  },
});

export const author = defineContentType({
  name: "Author",
  validator: v.object({
    name: v.string(),
    slug: v.string(),
    bio: v.optional(v.string()),
    avatar: v.optional(v.string()),
    email: v.optional(v.string()),
    socialLinks: v.optional(
      v.object({
        twitter: v.optional(v.string()),
        linkedin: v.optional(v.string()),
        github: v.optional(v.string()),
        website: v.optional(v.string()),
      })
    ),
  }),
  meta: {
    displayName: "Author",
    titleField: "name",
    slugField: "slug",
    fields: {
      name: { label: "Full Name", searchable: true },
      slug: { label: "URL Slug" },
      bio: { label: "Biography", renderAs: "richText" },
      avatar: { label: "Profile Photo", renderAs: "media" },
      email: { label: "Email Address" },
      socialLinks: { label: "Social Links", renderAs: "json" },
    },
  },
});

export const category = defineContentType({
  name: "Category",
  validator: v.object({
    name: v.string(),
    slug: v.string(),
    description: v.optional(v.string()),
    color: v.optional(v.string()),
    parentCategory: v.optional(v.string()),
  }),
  meta: {
    displayName: "Category",
    titleField: "name",
    slugField: "slug",
    fields: {
      name: { label: "Category Name", searchable: true },
      slug: { label: "URL Slug" },
      description: { label: "Description" },
      color: { label: "Color", description: "Hex color for UI display" },
      parentCategory: { label: "Parent Category" },
    },
  },
});

// =============================================================================
// TYPED HELPERS
// =============================================================================
// Create type-safe CRUD helpers for programmatic access.
// Use these in Convex functions for fully typed data access.

export const content = createTypedHelpers(components.cms, {
  blog: blogPost,
  author: author,
  category: category,
});
`;

export const BLOG_SCHEMA_DESCRIPTION = "Blog (post, author, category)";
