/**
 * Blog schema template
 *
 * Content types: blog_post, author, category
 */

export const BLOG_SCHEMA_TEMPLATE = `/**
 * Blog Content Types
 *
 * Defines the content structure for a blog with posts, authors, and categories.
 * These definitions are code-first and type-safe using Convex validators.
 *
 * Generated by: npx convex-cms init --template blog
 */

import { v } from "convex/values";
import { defineContentType } from "convex-cms";

export const blogPost = defineContentType({
  name: "blog_post",
  validator: v.object({
    title: v.string(),
    slug: v.string(),
    excerpt: v.optional(v.string()),
    content: v.string(),
    featuredImage: v.optional(v.string()),
    publishedAt: v.optional(v.number()),
    author: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
  }),
  meta: {
    displayName: "Blog Post",
    titleField: "title",
    slugField: "slug",
    fields: {
      title: { label: "Title", maxLength: 200 },
      slug: { label: "URL Slug", description: "URL-friendly identifier" },
      excerpt: { label: "Excerpt", maxLength: 300 },
      content: { label: "Content", renderAs: "richText" },
      featuredImage: { label: "Featured Image", renderAs: "media" },
      publishedAt: { label: "Publish Date", renderAs: "datetime" },
      author: { label: "Author" },
      tags: { label: "Tags", renderAs: "tags" },
    },
  },
});

export const author = defineContentType({
  name: "author",
  validator: v.object({
    name: v.string(),
    slug: v.string(),
    bio: v.optional(v.string()),
    avatar: v.optional(v.string()),
    email: v.optional(v.string()),
    socialLinks: v.optional(
      v.object({
        twitter: v.optional(v.string()),
        linkedin: v.optional(v.string()),
        github: v.optional(v.string()),
        website: v.optional(v.string()),
      })
    ),
  }),
  meta: {
    displayName: "Author",
    titleField: "name",
    slugField: "slug",
    fields: {
      name: { label: "Full Name" },
      slug: { label: "URL Slug" },
      bio: { label: "Biography", renderAs: "richText" },
      avatar: { label: "Profile Photo", renderAs: "media" },
      email: { label: "Email Address" },
      socialLinks: { label: "Social Links", renderAs: "json" },
    },
  },
});

export const category = defineContentType({
  name: "category",
  validator: v.object({
    name: v.string(),
    slug: v.string(),
    description: v.optional(v.string()),
    color: v.optional(v.string()),
    parentCategory: v.optional(v.string()),
  }),
  meta: {
    displayName: "Category",
    titleField: "name",
    slugField: "slug",
    fields: {
      name: { label: "Category Name" },
      slug: { label: "URL Slug" },
      description: { label: "Description" },
      color: { label: "Color", description: "Hex color for UI display" },
      parentCategory: { label: "Parent Category" },
    },
  },
});
`;

export const BLOG_SCHEMA_DESCRIPTION = "Blog (post, author, category)";
