/**
 * Documentation cms.ts template
 *
 * Content types: Documentation Page, Documentation Section, Navigation Tree
 * Includes typed helpers for programmatic access
 */

export const CMS_DOCS_TEMPLATE = `/**
 * CMS Setup - Documentation Template
 *
 * This file defines content types and creates typed helpers for type-safe access.
 *
 * Architecture:
 * - defineContentType() creates schema definitions for the admin API
 * - createTypedHelpers() creates type-safe CRUD helpers for programmatic access
 * - Both work together: definitions go to admin API, helpers provide typed access
 *
 * @example Type-safe queries in Convex functions
 * \`\`\`typescript
 * import { content } from "./cms";
 *
 * // Fully typed - data fields have correct types
 * const pages = await content.docPage.list(ctx, { status: "published" });
 * pages.page[0].data.title;  // string
 * \`\`\`
 *
 * Generated by: npx convex-cms init --template docs
 */

import { defineContentType, createTypedHelpers } from "convex-cms";
import { components } from "./_generated/api";
import { v } from "convex/values";

// =============================================================================
// CONTENT TYPE DEFINITIONS
// =============================================================================

export const docPage = defineContentType({
  name: "Documentation Page",
  validator: v.object({
    title: v.string(),
    slug: v.string(),
    content: v.string(),
    order: v.number(),
    sectionId: v.optional(v.string()),
    parentPageId: v.optional(v.string()),
    description: v.optional(v.string()),
    lastUpdatedBy: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    relatedPages: v.optional(v.array(v.string())),
  }),
  meta: {
    displayName: "Documentation Page",
    titleField: "title",
    slugField: "slug",
    fields: {
      title: { label: "Page Title", searchable: true },
      slug: { label: "URL Slug" },
      content: { label: "Content", renderAs: "richText", searchable: true },
      order: { label: "Display Order" },
      sectionId: { label: "Section" },
      parentPageId: { label: "Parent Page" },
      description: { label: "Meta Description", maxLength: 160 },
      lastUpdatedBy: { label: "Last Updated By" },
      tags: { label: "Tags", renderAs: "tags" },
      relatedPages: { label: "Related Pages", renderAs: "json" },
    },
  },
});

export const docSection = defineContentType({
  name: "Documentation Section",
  validator: v.object({
    name: v.string(),
    slug: v.string(),
    order: v.number(),
    description: v.optional(v.string()),
    icon: v.optional(v.string()),
    isCollapsible: v.optional(v.boolean()),
    defaultExpanded: v.optional(v.boolean()),
  }),
  meta: {
    displayName: "Documentation Section",
    titleField: "name",
    slugField: "slug",
    fields: {
      name: { label: "Section Name", searchable: true },
      slug: { label: "URL Slug" },
      order: { label: "Display Order" },
      description: { label: "Description" },
      icon: { label: "Icon", description: "Icon name or emoji" },
      isCollapsible: { label: "Collapsible" },
      defaultExpanded: { label: "Expanded by Default" },
    },
  },
});

export const docNavigation = defineContentType({
  name: "Navigation Tree",
  validator: v.object({
    name: v.string(),
    items: v.array(
      v.object({
        type: v.union(
          v.literal("page"),
          v.literal("section"),
          v.literal("link"),
          v.literal("divider")
        ),
        label: v.optional(v.string()),
        targetId: v.optional(v.string()),
        url: v.optional(v.string()),
        children: v.optional(v.array(v.string())),
      })
    ),
    isDefault: v.optional(v.boolean()),
  }),
  meta: {
    displayName: "Navigation Tree",
    titleField: "name",
    fields: {
      name: { label: "Navigation Name", searchable: true },
      items: { label: "Navigation Items", renderAs: "json" },
      isDefault: { label: "Default Navigation" },
    },
  },
});

// =============================================================================
// TYPED HELPERS
// =============================================================================
// Create type-safe CRUD helpers for programmatic access.
// Use these in Convex functions for fully typed data access.

export const content = createTypedHelpers(components.cms, {
  docPage: docPage,
  docSection: docSection,
  docNavigation: docNavigation,
});
`;

export const DOCS_SCHEMA_DESCRIPTION = "Documentation (page, section, navigation)";
