/**
 * Documentation cms.ts template
 *
 * Content types: Documentation Page, Documentation Section, Navigation Tree
 * Includes typed helpers for programmatic access
 */

export const CMS_DOCS_TEMPLATE = `/**
 * CMS Setup - Documentation Template
 *
 * Content types: Documentation Page, Documentation Section, Navigation Tree
 * Uses defineContentType() for schema definitions and createTypedHelpers() for typed CRUD access.
 *
 * @example Type-safe queries in Convex functions
 * \`\`\`typescript
 * import { content } from "./cms";
 *
 * const pages = await content.docPage.list(ctx, { status: "published" });
 * pages.page[0].data.title;  // string
 * \`\`\`
 *
 * Generated by: npx convex-cms init --template docs
 */

import { defineContentType, createTypedHelpers } from "convex-cms";
import { components } from "./_generated/api";
import { v } from "convex/values";

// =============================================================================
// CONTENT TYPE DEFINITIONS
// =============================================================================

export const docPage = defineContentType({
  name: "Documentation Page",
  validator: v.object({
    title: v.string(),
    slug: v.string(),
    content: v.string(),
    order: v.number(),
    sectionId: v.optional(v.string()),
    parentPageId: v.optional(v.string()),
    description: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    relatedPages: v.optional(v.array(v.string())),
    version: v.optional(v.string()),
  }),
  meta: {
    displayName: "Documentation Page",
    titleField: "title",
    slugField: "slug",
    fields: {
      title: { searchable: true, maxLength: 200 },
      slug: {
        pattern: "^[a-z0-9-]+$",
        patternMessage: "Only lowercase letters, numbers, and hyphens",
      },
      content: { renderAs: "richText", searchable: true },
      order: { min: 0, description: "Sort position within section" },
      sectionId: {
        renderAs: "reference",
        allowedContentTypes: ["documentation_section"],
      },
      parentPageId: {
        renderAs: "reference",
        allowedContentTypes: ["documentation_page"],
      },
      description: { maxLength: 160, description: "Search result excerpt" },
      tags: { renderAs: "tags", allowCreate: true },
      relatedPages: { renderAs: "json", description: "IDs of related pages" },
      version: {
        placeholder: "e.g., v2.0",
        description: "Documentation version this page applies to",
      },
    },
  },
});

export const docSection = defineContentType({
  name: "Documentation Section",
  validator: v.object({
    name: v.string(),
    slug: v.string(),
    order: v.number(),
    description: v.optional(v.string()),
    icon: v.optional(v.string()),
    isCollapsible: v.optional(v.boolean()),
    defaultExpanded: v.optional(v.boolean()),
  }),
  meta: {
    displayName: "Documentation Section",
    titleField: "name",
    slugField: "slug",
    fields: {
      name: { searchable: true, maxLength: 100 },
      slug: {
        pattern: "^[a-z0-9-]+$",
        patternMessage: "Only lowercase letters, numbers, and hyphens",
      },
      order: { min: 0 },
      description: { maxLength: 300 },
      icon: { placeholder: "e.g., \\u{1F4DA} or icon-name" },
      isCollapsible: { description: "Whether section can be collapsed in sidebar" },
      defaultExpanded: { description: "Expand by default in sidebar" },
    },
  },
});

export const docNavigation = defineContentType({
  name: "Navigation Tree",
  validator: v.object({
    name: v.string(),
    items: v.array(
      v.object({
        type: v.union(
          v.literal("page"),
          v.literal("section"),
          v.literal("link"),
          v.literal("divider")
        ),
        label: v.optional(v.string()),
        targetId: v.optional(v.string()),
        url: v.optional(v.string()),
        children: v.optional(v.array(v.string())),
      })
    ),
    isDefault: v.optional(v.boolean()),
  }),
  meta: {
    displayName: "Navigation Tree",
    titleField: "name",
    fields: {
      name: { searchable: true },
      items: { renderAs: "json" },
      isDefault: { description: "Use as the default navigation tree" },
    },
  },
});

// =============================================================================
// TYPED HELPERS
// =============================================================================

export const content = createTypedHelpers(components.cms, {
  docPage: docPage,
  docSection: docSection,
  docNavigation: docNavigation,
});
`;

export const DOCS_SCHEMA_DESCRIPTION = "Documentation (page, section, navigation)";
