/**
 * Documentation schema template
 *
 * Content types: doc_page, doc_section, doc_navigation
 */

export const DOCS_SCHEMA_TEMPLATE = `/**
 * Documentation Content Types
 *
 * Defines the content structure for technical documentation with pages,
 * sections, and navigation. Supports hierarchical organization.
 *
 * Generated by: npx convex-cms init --template docs
 */

import { v } from "convex/values";
import { defineContentType } from "convex-cms";

export const docPage = defineContentType({
  name: "doc_page",
  validator: v.object({
    title: v.string(),
    slug: v.string(),
    content: v.string(),
    order: v.number(),
    sectionId: v.optional(v.string()),
    parentPageId: v.optional(v.string()),
    description: v.optional(v.string()),
    lastUpdatedBy: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    relatedPages: v.optional(v.array(v.string())),
  }),
  meta: {
    displayName: "Documentation Page",
    titleField: "title",
    slugField: "slug",
    fields: {
      title: { label: "Page Title", searchable: true },
      slug: { label: "URL Slug" },
      content: { label: "Content", renderAs: "richText", searchable: true },
      order: { label: "Display Order" },
      sectionId: { label: "Section" },
      parentPageId: { label: "Parent Page" },
      description: { label: "Meta Description", maxLength: 160 },
      lastUpdatedBy: { label: "Last Updated By" },
      tags: { label: "Tags", renderAs: "tags" },
      relatedPages: { label: "Related Pages", renderAs: "json" },
    },
  },
});

export const docSection = defineContentType({
  name: "doc_section",
  validator: v.object({
    name: v.string(),
    slug: v.string(),
    order: v.number(),
    description: v.optional(v.string()),
    icon: v.optional(v.string()),
    isCollapsible: v.optional(v.boolean()),
    defaultExpanded: v.optional(v.boolean()),
  }),
  meta: {
    displayName: "Documentation Section",
    titleField: "name",
    slugField: "slug",
    fields: {
      name: { label: "Section Name" },
      slug: { label: "URL Slug" },
      order: { label: "Display Order" },
      description: { label: "Description" },
      icon: { label: "Icon", description: "Icon name or emoji" },
      isCollapsible: { label: "Collapsible" },
      defaultExpanded: { label: "Expanded by Default" },
    },
  },
});

export const docNavigation = defineContentType({
  name: "doc_navigation",
  validator: v.object({
    name: v.string(),
    items: v.array(
      v.object({
        type: v.union(
          v.literal("page"),
          v.literal("section"),
          v.literal("link"),
          v.literal("divider")
        ),
        label: v.optional(v.string()),
        targetId: v.optional(v.string()),
        url: v.optional(v.string()),
        children: v.optional(v.array(v.string())),
      })
    ),
    isDefault: v.optional(v.boolean()),
  }),
  meta: {
    displayName: "Navigation Tree",
    titleField: "name",
    fields: {
      name: { label: "Navigation Name" },
      items: { label: "Navigation Items", renderAs: "json" },
      isDefault: { label: "Default Navigation" },
    },
  },
});
`;

export const DOCS_SCHEMA_DESCRIPTION = "Documentation (page, section, navigation)";
