/**
 * E-commerce cms.ts template
 *
 * Content types: Product, Product Category, FAQ
 * Includes typed helpers for programmatic access
 */

export const CMS_ECOMMERCE_TEMPLATE = `/**
 * CMS Setup - E-commerce Template
 *
 * Content types: Product, Product Category, FAQ
 * Uses defineContentType() for schema definitions and createTypedHelpers() for typed CRUD access.
 *
 * @example Type-safe queries in Convex functions
 * \`\`\`typescript
 * import { content } from "./cms";
 *
 * const products = await content.product.list(ctx, { status: "published" });
 * products.page[0].data.name;  // string
 * \`\`\`
 *
 * Generated by: npx convex-cms init --template ecommerce
 */

import { defineContentType, createTypedHelpers } from "convex-cms";
import { components } from "./_generated/api";
import { v } from "convex/values";

// =============================================================================
// CONTENT TYPE DEFINITIONS
// =============================================================================

export const product = defineContentType({
  name: "Product",
  validator: v.object({
    name: v.string(),
    slug: v.string(),
    description: v.string(),
    shortDescription: v.optional(v.string()),
    price: v.number(),
    compareAtPrice: v.optional(v.number()),
    sku: v.optional(v.string()),
    featuredImage: v.optional(v.string()),
    gallery: v.optional(v.array(v.string())),
    category: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    inStock: v.optional(v.boolean()),
    featured: v.optional(v.boolean()),
    metaTitle: v.optional(v.string()),
    metaDescription: v.optional(v.string()),
  }),
  meta: {
    displayName: "Product",
    titleField: "name",
    slugField: "slug",
    fields: {
      name: { searchable: true, maxLength: 200 },
      slug: {
        pattern: "^[a-z0-9-]+$",
        patternMessage: "Only lowercase letters, numbers, and hyphens",
      },
      description: { renderAs: "richText", searchable: true },
      shortDescription: { maxLength: 300, description: "Product card text" },
      price: { min: 0, precision: 2, prefix: "$" },
      compareAtPrice: {
        min: 0,
        precision: 2,
        prefix: "$",
        description: "Original price for sale display",
      },
      sku: { placeholder: "e.g., PROD-001", maxLength: 50 },
      featuredImage: {
        renderAs: "media",
        allowedMimeTypes: ["image/*"],
        maxFileSize: 5 * 1024 * 1024,
      },
      gallery: { renderAs: "json", description: "Additional product image URLs" },
      category: { renderAs: "reference", allowedContentTypes: ["product_category"] },
      tags: { renderAs: "tags", allowCreate: true, maxTags: 15 },
      inStock: { description: "Whether the product is available for purchase" },
      featured: { description: "Feature on homepage and collection pages" },
      metaTitle: { maxLength: 60, placeholder: "SEO title" },
      metaDescription: { maxLength: 160, placeholder: "SEO description" },
    },
  },
});

export const productCategory = defineContentType({
  name: "Product Category",
  validator: v.object({
    name: v.string(),
    slug: v.string(),
    description: v.optional(v.string()),
    image: v.optional(v.string()),
    parentCategory: v.optional(v.string()),
    order: v.number(),
  }),
  meta: {
    displayName: "Product Category",
    titleField: "name",
    slugField: "slug",
    fields: {
      name: { searchable: true, maxLength: 100 },
      slug: {
        pattern: "^[a-z0-9-]+$",
        patternMessage: "Only lowercase letters, numbers, and hyphens",
      },
      description: { maxLength: 500 },
      image: { renderAs: "media", allowedMimeTypes: ["image/*"] },
      parentCategory: {
        renderAs: "reference",
        allowedContentTypes: ["product_category"],
      },
      order: { min: 0, description: "Display order in navigation" },
    },
  },
});

export const faq = defineContentType({
  name: "FAQ",
  validator: v.object({
    question: v.string(),
    answer: v.string(),
    category: v.optional(
      v.union(
        v.literal("Shipping"),
        v.literal("Returns"),
        v.literal("Payments"),
        v.literal("Products"),
        v.literal("General")
      )
    ),
    order: v.number(),
  }),
  meta: {
    displayName: "FAQ",
    titleField: "question",
    fields: {
      question: { searchable: true, maxLength: 200 },
      answer: { renderAs: "richText" },
      category: {
        renderAs: "select",
        options: [
          { value: "Shipping", label: "Shipping" },
          { value: "Returns", label: "Returns" },
          { value: "Payments", label: "Payments" },
          { value: "Products", label: "Products" },
          { value: "General", label: "General" },
        ],
      },
      order: { min: 0, description: "Display order" },
    },
  },
});

// =============================================================================
// TYPED HELPERS
// =============================================================================

export const content = createTypedHelpers(components.cms, {
  product: product,
  productCategory: productCategory,
  faq: faq,
});
`;

export const ECOMMERCE_SCHEMA_DESCRIPTION = "E-commerce (product, category, FAQ)";
