/**
 * Landing page cms.ts template
 *
 * Content types: Hero Section, Feature Block, Testimonial, CTA Section
 * Includes typed helpers for programmatic access
 */

export const CMS_LANDING_TEMPLATE = `/**
 * CMS Setup - Landing Page Template
 *
 * This file defines content types and creates typed helpers for type-safe access.
 *
 * Architecture:
 * - defineContentType() creates schema definitions for the admin API
 * - createTypedHelpers() creates type-safe CRUD helpers for programmatic access
 * - Both work together: definitions go to admin API, helpers provide typed access
 *
 * @example Type-safe queries in Convex functions
 * \`\`\`typescript
 * import { content } from "./cms";
 *
 * // Fully typed - data fields have correct types
 * const heroes = await content.hero.list(ctx, { status: "published" });
 * heroes.page[0].data.headline;  // string
 * \`\`\`
 *
 * Generated by: npx convex-cms init --template landing
 */

import { defineContentType, createTypedHelpers } from "convex-cms";
import { components } from "./_generated/api";
import { v } from "convex/values";

// =============================================================================
// CONTENT TYPE DEFINITIONS
// =============================================================================

export const heroSection = defineContentType({
  name: "Hero Section",
  validator: v.object({
    headline: v.string(),
    subheadline: v.optional(v.string()),
    ctaText: v.optional(v.string()),
    ctaUrl: v.optional(v.string()),
    secondaryCtaText: v.optional(v.string()),
    secondaryCtaUrl: v.optional(v.string()),
    backgroundImage: v.optional(v.string()),
    backgroundVideo: v.optional(v.string()),
    alignment: v.optional(
      v.union(v.literal("left"), v.literal("center"), v.literal("right"))
    ),
    theme: v.optional(v.union(v.literal("light"), v.literal("dark"))),
  }),
  meta: {
    displayName: "Hero Section",
    titleField: "headline",
    fields: {
      headline: { label: "Headline", searchable: true },
      subheadline: { label: "Subheadline" },
      ctaText: { label: "Primary CTA Text" },
      ctaUrl: { label: "Primary CTA URL" },
      secondaryCtaText: { label: "Secondary CTA Text" },
      secondaryCtaUrl: { label: "Secondary CTA URL" },
      backgroundImage: { label: "Background Image", renderAs: "media" },
      backgroundVideo: { label: "Background Video URL" },
      alignment: {
        label: "Text Alignment",
        renderAs: "select",
        options: [
          { value: "left", label: "Left" },
          { value: "center", label: "Center" },
          { value: "right", label: "Right" },
        ],
      },
      theme: {
        label: "Color Theme",
        renderAs: "select",
        options: [
          { value: "light", label: "Light" },
          { value: "dark", label: "Dark" },
        ],
      },
    },
  },
});

export const featureBlock = defineContentType({
  name: "Feature Block",
  validator: v.object({
    title: v.string(),
    description: v.string(),
    icon: v.optional(v.string()),
    image: v.optional(v.string()),
    order: v.number(),
    link: v.optional(v.string()),
    linkText: v.optional(v.string()),
  }),
  meta: {
    displayName: "Feature Block",
    titleField: "title",
    fields: {
      title: { label: "Feature Title", searchable: true },
      description: { label: "Description", renderAs: "richText" },
      icon: { label: "Icon", description: "Icon name or emoji" },
      image: { label: "Feature Image", renderAs: "media" },
      order: { label: "Display Order" },
      link: { label: "Learn More URL" },
      linkText: { label: "Link Text" },
    },
  },
});

export const testimonial = defineContentType({
  name: "Testimonial",
  validator: v.object({
    quote: v.string(),
    authorName: v.string(),
    authorTitle: v.optional(v.string()),
    company: v.optional(v.string()),
    avatar: v.optional(v.string()),
    companyLogo: v.optional(v.string()),
    rating: v.optional(v.number()),
    featured: v.optional(v.boolean()),
  }),
  meta: {
    displayName: "Testimonial",
    titleField: "authorName",
    fields: {
      quote: { label: "Quote", renderAs: "richText", searchable: true },
      authorName: { label: "Author Name" },
      authorTitle: { label: "Author Title" },
      company: { label: "Company Name" },
      avatar: { label: "Author Photo", renderAs: "media" },
      companyLogo: { label: "Company Logo", renderAs: "media" },
      rating: { label: "Rating", min: 1, max: 5 },
      featured: { label: "Featured Testimonial" },
    },
  },
});

export const ctaSection = defineContentType({
  name: "CTA Section",
  validator: v.object({
    headline: v.string(),
    description: v.optional(v.string()),
    buttonText: v.string(),
    buttonUrl: v.string(),
    secondaryText: v.optional(v.string()),
    secondaryUrl: v.optional(v.string()),
    backgroundColor: v.optional(v.string()),
    backgroundImage: v.optional(v.string()),
  }),
  meta: {
    displayName: "CTA Section",
    titleField: "headline",
    fields: {
      headline: { label: "Headline", searchable: true },
      description: { label: "Description" },
      buttonText: { label: "Button Text" },
      buttonUrl: { label: "Button URL" },
      secondaryText: { label: "Secondary Button Text" },
      secondaryUrl: { label: "Secondary Button URL" },
      backgroundColor: { label: "Background Color" },
      backgroundImage: { label: "Background Image", renderAs: "media" },
    },
  },
});

// =============================================================================
// TYPED HELPERS
// =============================================================================
// Create type-safe CRUD helpers for programmatic access.
// Use these in Convex functions for fully typed data access.

export const content = createTypedHelpers(components.cms, {
  hero: heroSection,
  feature: featureBlock,
  testimonial: testimonial,
  cta: ctaSection,
});
`;

export const LANDING_SCHEMA_DESCRIPTION = "Landing Page (hero, features, testimonials)";
