/**
 * Landing page schema template
 *
 * Content types: hero_section, feature_block, testimonial, cta_section
 */

export const LANDING_SCHEMA_TEMPLATE = `/**
 * Landing Page Content Types
 *
 * Defines the content structure for marketing landing pages with modular
 * components like hero sections, features, testimonials, and CTAs.
 *
 * Generated by: npx convex-cms init --template landing
 */

import { v } from "convex/values";
import { defineContentType } from "convex-cms";

export const heroSection = defineContentType({
  name: "hero_section",
  validator: v.object({
    headline: v.string(),
    subheadline: v.optional(v.string()),
    ctaText: v.optional(v.string()),
    ctaUrl: v.optional(v.string()),
    secondaryCtaText: v.optional(v.string()),
    secondaryCtaUrl: v.optional(v.string()),
    backgroundImage: v.optional(v.string()),
    backgroundVideo: v.optional(v.string()),
    alignment: v.optional(
      v.union(v.literal("left"), v.literal("center"), v.literal("right"))
    ),
    theme: v.optional(v.union(v.literal("light"), v.literal("dark"))),
  }),
  meta: {
    displayName: "Hero Section",
    titleField: "headline",
    fields: {
      headline: { label: "Headline", searchable: true },
      subheadline: { label: "Subheadline" },
      ctaText: { label: "Primary CTA Text" },
      ctaUrl: { label: "Primary CTA URL" },
      secondaryCtaText: { label: "Secondary CTA Text" },
      secondaryCtaUrl: { label: "Secondary CTA URL" },
      backgroundImage: { label: "Background Image", renderAs: "media" },
      backgroundVideo: { label: "Background Video URL" },
      alignment: { label: "Text Alignment" },
      theme: { label: "Color Theme" },
    },
  },
});

export const featureBlock = defineContentType({
  name: "feature_block",
  validator: v.object({
    title: v.string(),
    description: v.string(),
    icon: v.optional(v.string()),
    image: v.optional(v.string()),
    order: v.number(),
    link: v.optional(v.string()),
    linkText: v.optional(v.string()),
  }),
  meta: {
    displayName: "Feature Block",
    titleField: "title",
    fields: {
      title: { label: "Feature Title", searchable: true },
      description: { label: "Description", renderAs: "richText" },
      icon: { label: "Icon", description: "Icon name or emoji" },
      image: { label: "Feature Image", renderAs: "media" },
      order: { label: "Display Order" },
      link: { label: "Learn More URL" },
      linkText: { label: "Link Text" },
    },
  },
});

export const testimonial = defineContentType({
  name: "testimonial",
  validator: v.object({
    quote: v.string(),
    authorName: v.string(),
    authorTitle: v.optional(v.string()),
    company: v.optional(v.string()),
    avatar: v.optional(v.string()),
    companyLogo: v.optional(v.string()),
    rating: v.optional(v.number()),
    featured: v.optional(v.boolean()),
  }),
  meta: {
    displayName: "Testimonial",
    titleField: "authorName",
    fields: {
      quote: { label: "Quote", renderAs: "richText" },
      authorName: { label: "Author Name" },
      authorTitle: { label: "Author Title" },
      company: { label: "Company Name" },
      avatar: { label: "Author Photo", renderAs: "media" },
      companyLogo: { label: "Company Logo", renderAs: "media" },
      rating: { label: "Rating", min: 1, max: 5 },
      featured: { label: "Featured Testimonial" },
    },
  },
});

export const ctaSection = defineContentType({
  name: "cta_section",
  validator: v.object({
    headline: v.string(),
    description: v.optional(v.string()),
    buttonText: v.string(),
    buttonUrl: v.string(),
    secondaryText: v.optional(v.string()),
    secondaryUrl: v.optional(v.string()),
    backgroundColor: v.optional(v.string()),
    backgroundImage: v.optional(v.string()),
  }),
  meta: {
    displayName: "CTA Section",
    titleField: "headline",
    fields: {
      headline: { label: "Headline" },
      description: { label: "Description" },
      buttonText: { label: "Button Text" },
      buttonUrl: { label: "Button URL" },
      secondaryText: { label: "Secondary Button Text" },
      secondaryUrl: { label: "Secondary Button URL" },
      backgroundColor: { label: "Background Color" },
      backgroundImage: { label: "Background Image", renderAs: "media" },
    },
  },
});
`;

export const LANDING_SCHEMA_DESCRIPTION = "Landing Page (hero, features, testimonials)";
