/**
 * Landing page cms.ts template
 *
 * Content types: Page, Hero Section, Feature Block, Testimonial, FAQ, CTA Section
 * Includes typed helpers for programmatic access
 */

export const CMS_LANDING_TEMPLATE = `/**
 * CMS Setup - Landing Page Template
 *
 * Content types: Page, Hero Section, Feature Block, Testimonial, FAQ, CTA Section
 * Uses defineContentType() for schema definitions and createTypedHelpers() for typed CRUD access.
 *
 * @example Type-safe queries in Convex functions
 * \`\`\`typescript
 * import { content } from "./cms";
 *
 * const heroes = await content.hero.list(ctx, { status: "published" });
 * heroes.page[0].data.headline;  // string
 * \`\`\`
 *
 * Generated by: npx convex-cms init --template landing
 */

import { defineContentType, createTypedHelpers } from "convex-cms";
import { components } from "./_generated/api";
import { v } from "convex/values";

// =============================================================================
// CONTENT TYPE DEFINITIONS
// =============================================================================

export const page = defineContentType({
  name: "Page",
  validator: v.object({
    title: v.string(),
    slug: v.string(),
    content: v.string(),
    metaTitle: v.optional(v.string()),
    metaDescription: v.optional(v.string()),
    featuredImage: v.optional(v.string()),
  }),
  meta: {
    displayName: "Page",
    titleField: "title",
    slugField: "slug",
    fields: {
      title: { searchable: true, maxLength: 200 },
      slug: {
        pattern: "^[a-z0-9-]+$",
        patternMessage: "Only lowercase letters, numbers, and hyphens",
      },
      content: { renderAs: "richText", searchable: true },
      metaTitle: {
        maxLength: 60,
        placeholder: "SEO title",
        description: "Title shown in search results",
      },
      metaDescription: {
        maxLength: 160,
        placeholder: "SEO description",
      },
      featuredImage: { renderAs: "media", allowedMimeTypes: ["image/*"] },
    },
  },
});

export const heroSection = defineContentType({
  name: "Hero Section",
  validator: v.object({
    headline: v.string(),
    subheadline: v.optional(v.string()),
    ctaText: v.optional(v.string()),
    ctaUrl: v.optional(v.string()),
    secondaryCtaText: v.optional(v.string()),
    secondaryCtaUrl: v.optional(v.string()),
    backgroundImage: v.optional(v.string()),
    alignment: v.optional(
      v.union(v.literal("left"), v.literal("center"), v.literal("right"))
    ),
    theme: v.optional(v.union(v.literal("light"), v.literal("dark"))),
  }),
  meta: {
    displayName: "Hero Section",
    titleField: "headline",
    fields: {
      headline: { searchable: true, maxLength: 120 },
      subheadline: { maxLength: 200 },
      ctaText: { placeholder: "Get Started", maxLength: 50 },
      ctaUrl: { placeholder: "https://...", description: "Primary button link" },
      secondaryCtaText: { placeholder: "Learn More", maxLength: 50 },
      secondaryCtaUrl: { placeholder: "https://...", description: "Secondary button link" },
      backgroundImage: { renderAs: "media", allowedMimeTypes: ["image/*"] },
      alignment: {
        renderAs: "select",
        options: [
          { value: "left", label: "Left" },
          { value: "center", label: "Center" },
          { value: "right", label: "Right" },
        ],
      },
      theme: {
        renderAs: "select",
        options: [
          { value: "light", label: "Light" },
          { value: "dark", label: "Dark" },
        ],
      },
    },
  },
});

export const featureBlock = defineContentType({
  name: "Feature Block",
  validator: v.object({
    title: v.string(),
    description: v.string(),
    icon: v.optional(v.string()),
    image: v.optional(v.string()),
    order: v.number(),
    link: v.optional(v.string()),
    linkText: v.optional(v.string()),
  }),
  meta: {
    displayName: "Feature Block",
    titleField: "title",
    fields: {
      title: { searchable: true, maxLength: 100 },
      description: { renderAs: "richText" },
      icon: { placeholder: "e.g., \\u{1F680} or icon-name" },
      image: { renderAs: "media", allowedMimeTypes: ["image/*"] },
      order: { min: 0, description: "Display order" },
      link: { placeholder: "https://...", description: "Learn more URL" },
      linkText: { maxLength: 50, placeholder: "Learn more" },
    },
  },
});

export const testimonial = defineContentType({
  name: "Testimonial",
  validator: v.object({
    quote: v.string(),
    authorName: v.string(),
    authorTitle: v.optional(v.string()),
    company: v.optional(v.string()),
    avatar: v.optional(v.string()),
    companyLogo: v.optional(v.string()),
    rating: v.optional(v.number()),
    featured: v.optional(v.boolean()),
  }),
  meta: {
    displayName: "Testimonial",
    titleField: "authorName",
    fields: {
      quote: { renderAs: "richText", searchable: true, maxLength: 1000 },
      authorName: { maxLength: 100 },
      authorTitle: { placeholder: "e.g., CTO", maxLength: 100 },
      company: { maxLength: 100 },
      avatar: {
        renderAs: "media",
        allowedMimeTypes: ["image/*"],
        maxFileSize: 2 * 1024 * 1024,
      },
      companyLogo: {
        renderAs: "media",
        allowedMimeTypes: ["image/*"],
        maxFileSize: 1 * 1024 * 1024,
      },
      rating: { min: 1, max: 5, step: 1, precision: 0 },
      featured: { description: "Show in featured testimonials section" },
    },
  },
});

export const faq = defineContentType({
  name: "FAQ",
  validator: v.object({
    question: v.string(),
    answer: v.string(),
    category: v.optional(v.string()),
    order: v.number(),
  }),
  meta: {
    displayName: "FAQ",
    titleField: "question",
    fields: {
      question: { searchable: true, maxLength: 200 },
      answer: { renderAs: "richText" },
      category: { placeholder: "e.g., Billing, Technical" },
      order: { min: 0, description: "Display order" },
    },
  },
});

export const ctaSection = defineContentType({
  name: "CTA Section",
  validator: v.object({
    headline: v.string(),
    description: v.optional(v.string()),
    buttonText: v.string(),
    buttonUrl: v.string(),
    secondaryText: v.optional(v.string()),
    secondaryUrl: v.optional(v.string()),
    backgroundColor: v.optional(v.string()),
    backgroundImage: v.optional(v.string()),
  }),
  meta: {
    displayName: "CTA Section",
    titleField: "headline",
    fields: {
      headline: { searchable: true, maxLength: 100 },
      description: { maxLength: 300 },
      buttonText: { maxLength: 50 },
      buttonUrl: { placeholder: "https://..." },
      secondaryText: { maxLength: 50 },
      secondaryUrl: { placeholder: "https://..." },
      backgroundColor: { placeholder: "#3B82F6", description: "Hex background color" },
      backgroundImage: { renderAs: "media", allowedMimeTypes: ["image/*"] },
    },
  },
});

// =============================================================================
// TYPED HELPERS
// =============================================================================

export const content = createTypedHelpers(components.cms, {
  page: page,
  hero: heroSection,
  feature: featureBlock,
  testimonial: testimonial,
  faq: faq,
  cta: ctaSection,
});
`;

export const LANDING_SCHEMA_DESCRIPTION = "Landing Page (hero, features, testimonials, FAQ)";
