/**
 * Admin API template for CMS Admin UI
 *
 * Generated by: npx convex-cms init
 *
 * Uses destructuring exports pattern and imports content types from cms.ts.
 */

import type { SchemaTemplate } from "./schemas/index.js";

interface AdminTemplateConfig {
  contentTypeImports: string;
  contentTypesObject: string;
}

const TEMPLATE_CONFIGS: Record<SchemaTemplate, AdminTemplateConfig> = {
  blog: {
    contentTypeImports: "blogPost, author, category",
    contentTypesObject: "blogPost, author, category",
  },
  docs: {
    contentTypeImports: "docPage, docSection, docNavigation",
    contentTypesObject: "docPage, docSection, docNavigation",
  },
  landing: {
    contentTypeImports: "page, heroSection, featureBlock, testimonial, faq, ctaSection",
    contentTypesObject: "page, heroSection, featureBlock, testimonial, faq, ctaSection",
  },
  ecommerce: {
    contentTypeImports: "product, productCategory, faq",
    contentTypesObject: "product, productCategory, faq",
  },
  blank: {
    contentTypeImports: "blogPost",
    contentTypesObject: "blogPost",
  },
};

export function getAdminTemplate(template: SchemaTemplate): string {
  const config = TEMPLATE_CONFIGS[template];

  return `/**
 * Admin API for CMS Admin UI
 *
 * Usage:
 * 1. Run your Convex dev server: \`npx convex dev\`
 * 2. Launch the admin UI: \`npx convex-cms admin\`
 * 3. Or embed in your app: \`<CmsAdmin convexUrl={...} />\`
 */

import { components } from "./_generated/api";
import { defineAdminAPI } from "convex-cms";
import { ${config.contentTypeImports} } from "./cms";

export const {
  // Dashboard
  getDashboardStats,
  // Content Types
  listContentTypes,
  getContentType,
  createContentType,
  updateContentType,
  deleteContentType,
  syncCodeDefinedTypes,
  checkSchemaDrift,
  // Content Entries
  listEntries,
  getEntry,
  createEntry,
  updateEntry,
  publishEntry,
  unpublishEntry,
  deleteEntry,
  duplicateEntry,
  scheduleEntry,
  cancelScheduledEntry,
  getScheduledEntries,
  restoreEntry,
  getEntryBySlug,
  getEntryBySlugAndTypeName,
  // Bulk Operations
  bulkPublish,
  bulkUnpublish,
  bulkDelete,
  bulkUpdate,
  bulkRestore,
  // Trash
  getTrashConfig,
  listTrash,
  getTrashStats,
  updateTrashConfig,
  emptyTrash,
  runTrashCleanup,
  // Content Lock
  checkContentLock,
  listLockedContent,
  acquireContentLock,
  releaseContentLock,
  renewContentLock,
  forceReleaseContentLock,
  // Versions
  getVersionHistory,
  getVersion,
  compareVersions,
  rollbackVersion,
  // Media Assets
  listMediaAssets,
  getMediaAsset,
  createMediaAsset,
  updateMediaAsset,
  deleteMediaAsset,
  restoreMediaAsset,
  permanentDeleteMediaAsset,
  bulkPermanentDeleteMediaAssets,
  moveMediaAssets,
  getMediaTrashCount,
  // Media Folders
  listMediaFolders,
  getMediaFolder,
  getMediaFolderTree,
  createMediaFolder,
  updateMediaFolder,
  moveMediaFolder,
  deleteMediaFolder,
  restoreMediaFolder,
  // Media Variants
  listMediaVariants,
  getMediaVariant,
  getBestMediaVariant,
  getMediaResponsiveSrcset,
  getMediaVariantPresets,
  getMediaAssetWithVariants,
  createMediaVariant,
  requestMediaVariantGeneration,
  deleteMediaVariant,
  deleteMediaAssetVariants,
  generateMediaVariantsFromPresets,
  restoreMediaVariant,
  // Upload
  generateUploadUrl,
  // Taxonomies
  getTaxonomy,
  listTaxonomies,
  createTaxonomy,
  updateTaxonomy,
  deleteTaxonomy,
  restoreTaxonomy,
  // Terms
  getTerm,
  listTerms,
  getTermsHierarchy,
  suggestTerms,
  countTerms,
  createTerm,
  updateTerm,
  deleteTerm,
  restoreTerm,
  // Entry-Term Relations
  getTermsByEntry,
  getEntriesByTerm,
  setEntryTerms,
  addTermToEntry,
  removeTermFromEntry,
  createTermAndAddToEntry,
  // Media-Term Relations
  getTermsByMedia,
  getMediaByTerm,
  setMediaTerms,
  addTermToMedia,
  removeTermFromMedia,
  createTermAndAddToMedia,
  // Settings
  getSettings,
  updateSettings,
  resetSettings,
} = defineAdminAPI(components.cms, {
  contentTypes: { ${config.contentTypesObject} },
});
`;
}

// Legacy export for backwards compatibility
export const ADMIN_TEMPLATE = getAdminTemplate("blank");
