/**
 * CMS Client template - Blank starter
 *
 * Generated by: npx convex-cms init
 */

export const CMS_CLIENT_TEMPLATE = `/**
 * CMS Setup
 *
 * This file defines content types and creates typed helpers for type-safe access.
 *
 * Architecture:
 * - defineContentType() creates schema definitions for the admin API
 * - createTypedHelpers() creates type-safe CRUD helpers for programmatic access
 * - Both work together: definitions go to admin API, helpers provide typed access
 *
 * @example Type-safe queries in Convex functions
 * \`\`\`typescript
 * import { content } from "./cms";
 *
 * // Fully typed - data fields have correct types
 * const items = await content.blog.list(ctx, { status: "published" });
 * items.page[0].data.title;  // string
 * \`\`\`
 */

import { defineContentType, createTypedHelpers } from "convex-cms";
import { components } from "./_generated/api";
import { v } from "convex/values";

// =============================================================================
// CONTENT TYPE DEFINITIONS
// =============================================================================
// Define your content types here. These are automatically registered and
// available in the admin API. Code-defined types show as "Native Fields"
// and cannot be edited/deleted through the admin UI.

export const blogPost = defineContentType({
  name: "Blog Post",
  validator: v.object({
    title: v.string(),
    slug: v.string(),
    content: v.string(),
    excerpt: v.optional(v.string()),
    publishedAt: v.optional(v.number()),
  }),
  meta: {
    displayName: "Blog Post",
    titleField: "title",
    slugField: "slug",
    fields: {
      title: {
        label: "Title",
        maxLength: 200,
        searchable: true,
      },
      slug: {
        label: "URL Slug",
        description: "URL-friendly identifier",
        pattern: "^[a-z0-9-]+$",
        patternMessage: "Only lowercase letters, numbers, and hyphens",
      },
      content: {
        label: "Content",
        renderAs: "richText",
      },
      excerpt: {
        label: "Excerpt",
        maxLength: 300,
      },
      publishedAt: {
        label: "Publish Date",
        renderAs: "datetime",
      },
    },
  },
});

// =============================================================================
// TYPED HELPERS
// =============================================================================
// Create type-safe CRUD helpers for programmatic access.
// Use these in Convex functions for fully typed data access.

export const content = createTypedHelpers(components.cms, {
  blog: blogPost,
});
`;
