/**
 * CMS Client template
 *
 * Generated by: npx convex-cms init
 */

export const CMS_CLIENT_TEMPLATE = `/**
 * CMS Setup
 *
 * Uses the unified createCms API for type-safe content management.
 * Define content types with defineContent() and export the admin API.
 *
 * @example
 * \`\`\`typescript
 * import { blogPost, admin } from "./cms";
 *
 * // Use in a mutation (typed helpers)
 * export const createPost = mutation({
 *   args: { title: v.string() },
 *   handler: async (ctx, args) => {
 *     return await blogPost.create(ctx, {
 *       data: { title: args.title },
 *     });
 *   },
 * });
 * \`\`\`
 */

import { createCms } from "convex-cms";
import { v } from "convex/values";
import { components } from "./_generated/api";
import cmsConfig from "./cms.config";

const cms = createCms(components.convexCms, cmsConfig);

// Define your content types here
export const blogPost = cms.defineContent({
  name: "Blog Post",
  fields: v.object({
    title: v.string(),
    content: v.string(),
    publishedAt: v.optional(v.number()),
  }),
  display: {
    titleField: "title",
    icon: "📝",
  },
});

// Export admin API for the admin UI
export const admin = cms.admin;

// For advanced usage, you can also access CmsClient namespaces:
// cms.contentTypes, cms.contentEntries, cms.versions, etc.
`;
