/**
 * CMS Config template
 *
 * Generated by: npx convex-cms init
 */

export const CMS_CONFIG_TEMPLATE = `/**
 * Unified CMS Configuration
 *
 * This file is the single source of truth for CMS settings.
 * It's used by both createCmsClient (for your app) and defineAdminAPI (for the admin UI).
 *
 * Generated by: npx convex-cms init
 */

import { defineCmsConfig } from "convex-cms";

export default defineCmsConfig({
  // =========================================================================
  // SHARED - Used by both createCmsClient and defineAdminAPI
  // =========================================================================

  features: {
    versioning: true,
    scheduling: true,
    localization: false,
    mediaManagement: true,
    softDelete: true,
  },

  // Uncomment to configure localization:
  // locale: {
  //   defaultLocale: "en-US",
  //   supportedLocales: ["en-US", "es-ES", "fr-FR"],
  //   fallbackChains: {
  //     "es-ES": ["en-US"],
  //     "fr-FR": ["en-US"],
  //   },
  // },

  limits: {
    maxVersionsPerEntry: 50,
  },

  // =========================================================================
  // CLIENT-SPECIFIC - Only used by createCmsClient
  // =========================================================================

  client: {
    // Uncomment to enable RBAC:
    // customRoles: [
    //   {
    //     name: "editor",
    //     displayName: "Editor",
    //     description: "Can create and edit content",
    //     permissions: [
    //       { resource: "contentTypes", action: "read" },
    //       { resource: "contentEntries", action: "create" },
    //       { resource: "contentEntries", action: "read" },
    //       { resource: "contentEntries", action: "update" },
    //     ],
    //   },
    // ],

    // Uncomment to enable RBAC:
    // getUserRole: async (ctx, { userId }) => {
    //   if (!userId) return null;
    //   const user = await ctx.db.get(userId);
    //   return user?.cmsRole ?? null;
    // },
  },

  // =========================================================================
  // ADMIN-SPECIFIC - Only used by defineAdminAPI
  // =========================================================================

  admin: {
    // Uncomment for production auth:
    // auth: async (ctx, operation) => {
    //   const identity = await ctx.auth.getUserIdentity();
    //   if (!identity) throw new Error("Not authenticated");
    //   return identity.subject;
    // },
  },
});
`;
