/**
 * Content queries template
 *
 * Generated by: npx convex-cms init
 *
 * Shows how to use typed helpers from cms.ts in public queries.
 */

import type { SchemaTemplate } from "./schemas/index.js";

export function getContentTemplate(template: SchemaTemplate): string {
  switch (template) {
    case "blog":
      return CONTENT_BLOG_TEMPLATE;
    case "docs":
      return CONTENT_DOCS_TEMPLATE;
    case "landing":
      return CONTENT_LANDING_TEMPLATE;
    case "blank":
    default:
      return CONTENT_BLANK_TEMPLATE;
  }
}

const CONTENT_BLANK_TEMPLATE = `/**
 * Public content queries for the frontend
 *
 * These queries use the typed helpers from cms.ts for type-safe data access.
 * The content helpers provide full TypeScript inference for all fields.
 */

import { query } from "./_generated/server";
import { content } from "./cms";

export const getBlogPosts = query({
  args: {},
  handler: async (ctx) => {
    // Using typed helper - result.page[].data is fully typed
    const result = await content.blog.list(ctx, { status: "published" });

    // Return entries with data flattened for easier frontend consumption
    return result.page.map((entry) => ({
      _id: entry._id,
      ...entry.data,
    }));
  },
});
`;

const CONTENT_BLOG_TEMPLATE = `/**
 * Public content queries for the frontend - Blog Template
 *
 * These queries use the typed helpers from cms.ts for type-safe data access.
 * The content helpers provide full TypeScript inference for all fields.
 */

import { query } from "./_generated/server";
import { v } from "convex/values";
import { content } from "./cms";

export const getBlogPosts = query({
  args: {},
  handler: async (ctx) => {
    const result = await content.blog.list(ctx, { status: "published" });

    return result.page.map((entry) => ({
      _id: entry._id,
      ...entry.data,
    }));
  },
});

export const getBlogPostBySlug = query({
  args: { slug: v.string() },
  handler: async (ctx, { slug }) => {
    const result = await content.blog.list(ctx, { status: "published" });

    const post = result.page.find((entry) => entry.data.slug === slug);
    if (!post) return null;

    return {
      _id: post._id,
      ...post.data,
    };
  },
});

export const getAuthors = query({
  args: {},
  handler: async (ctx) => {
    const result = await content.author.list(ctx, { status: "published" });

    return result.page.map((entry) => ({
      _id: entry._id,
      ...entry.data,
    }));
  },
});

export const getCategories = query({
  args: {},
  handler: async (ctx) => {
    const result = await content.category.list(ctx, { status: "published" });

    return result.page.map((entry) => ({
      _id: entry._id,
      ...entry.data,
    }));
  },
});
`;

const CONTENT_DOCS_TEMPLATE = `/**
 * Public content queries for the frontend - Documentation Template
 *
 * These queries use the typed helpers from cms.ts for type-safe data access.
 * The content helpers provide full TypeScript inference for all fields.
 */

import { query } from "./_generated/server";
import { v } from "convex/values";
import { content } from "./cms";

export const getDocPages = query({
  args: {},
  handler: async (ctx) => {
    const result = await content.docPage.list(ctx, { status: "published" });

    return result.page.map((entry) => ({
      _id: entry._id,
      ...entry.data,
    }));
  },
});

export const getDocPageBySlug = query({
  args: { slug: v.string() },
  handler: async (ctx, { slug }) => {
    const result = await content.docPage.list(ctx, { status: "published" });

    const page = result.page.find((entry) => entry.data.slug === slug);
    if (!page) return null;

    return {
      _id: page._id,
      ...page.data,
    };
  },
});

export const getDocSections = query({
  args: {},
  handler: async (ctx) => {
    const result = await content.docSection.list(ctx, { status: "published" });

    // Sort by order
    return result.page
      .map((entry) => ({
        _id: entry._id,
        ...entry.data,
      }))
      .sort((a, b) => a.order - b.order);
  },
});

export const getDocNavigation = query({
  args: {},
  handler: async (ctx) => {
    const result = await content.docNavigation.list(ctx, { status: "published" });

    // Find the default navigation
    const defaultNav = result.page.find((entry) => entry.data.isDefault);
    if (!defaultNav) {
      // Return first nav if no default
      const first = result.page[0];
      if (!first) return null;
      return { _id: first._id, ...first.data };
    }

    return {
      _id: defaultNav._id,
      ...defaultNav.data,
    };
  },
});
`;

const CONTENT_LANDING_TEMPLATE = `/**
 * Public content queries for the frontend - Landing Page Template
 *
 * These queries use the typed helpers from cms.ts for type-safe data access.
 * The content helpers provide full TypeScript inference for all fields.
 */

import { query } from "./_generated/server";
import { content } from "./cms";

export const getHeroSections = query({
  args: {},
  handler: async (ctx) => {
    const result = await content.hero.list(ctx, { status: "published" });

    return result.page.map((entry) => ({
      _id: entry._id,
      ...entry.data,
    }));
  },
});

export const getFeatureBlocks = query({
  args: {},
  handler: async (ctx) => {
    const result = await content.feature.list(ctx, { status: "published" });

    // Sort by order
    return result.page
      .map((entry) => ({
        _id: entry._id,
        ...entry.data,
      }))
      .sort((a, b) => a.order - b.order);
  },
});

export const getTestimonials = query({
  args: {},
  handler: async (ctx) => {
    const result = await content.testimonial.list(ctx, { status: "published" });

    return result.page.map((entry) => ({
      _id: entry._id,
      ...entry.data,
    }));
  },
});

export const getFeaturedTestimonials = query({
  args: {},
  handler: async (ctx) => {
    const result = await content.testimonial.list(ctx, { status: "published" });

    // Filter to featured only
    return result.page
      .filter((entry) => entry.data.featured)
      .map((entry) => ({
        _id: entry._id,
        ...entry.data,
      }));
  },
});

export const getCtaSections = query({
  args: {},
  handler: async (ctx) => {
    const result = await content.cta.list(ctx, { status: "published" });

    return result.page.map((entry) => ({
      _id: entry._id,
      ...entry.data,
    }));
  },
});
`;
