import { components } from "./_generated/api";
import { defineAdminAPI } from "convex-cms";
import { changelogEntry, roadmapItem } from "./cms";

export const {
	// Dashboard
	getDashboardStats,
	// Content Types
	listContentTypes,
	getContentType,
	createContentType,
	updateContentType,
	deleteContentType,
	syncCodeDefinedTypes,
	checkSchemaDrift,
	// Content Entries
	listEntries,
	getEntry,
	createEntry,
	updateEntry,
	publishEntry,
	unpublishEntry,
	deleteEntry,
	duplicateEntry,
	scheduleEntry,
	cancelScheduledEntry,
	getScheduledEntries,
	restoreEntry,
	getEntryBySlug,
	getEntryBySlugAndTypeName,
	// Bulk Operations
	bulkPublish,
	bulkUnpublish,
	bulkDelete,
	bulkUpdate,
	bulkRestore,
	// Trash
	getTrashConfig,
	listTrash,
	getTrashStats,
	updateTrashConfig,
	emptyTrash,
	runTrashCleanup,
	// Content Lock
	checkContentLock,
	listLockedContent,
	acquireContentLock,
	releaseContentLock,
	renewContentLock,
	forceReleaseContentLock,
	// Versions
	getVersionHistory,
	getVersion,
	compareVersions,
	rollbackVersion,
	// Media Assets
	listMediaAssets,
	getMediaAsset,
	createMediaAsset,
	updateMediaAsset,
	deleteMediaAsset,
	restoreMediaAsset,
	permanentDeleteMediaAsset,
	bulkPermanentDeleteMediaAssets,
	moveMediaAssets,
	getMediaTrashCount,
	// Media Folders
	listMediaFolders,
	getMediaFolder,
	getMediaFolderTree,
	createMediaFolder,
	updateMediaFolder,
	moveMediaFolder,
	deleteMediaFolder,
	restoreMediaFolder,
	// Media Variants
	listMediaVariants,
	getMediaVariant,
	getBestMediaVariant,
	getMediaResponsiveSrcset,
	getMediaVariantPresets,
	getMediaAssetWithVariants,
	createMediaVariant,
	requestMediaVariantGeneration,
	deleteMediaVariant,
	deleteMediaAssetVariants,
	generateMediaVariantsFromPresets,
	restoreMediaVariant,
	// Upload
	generateUploadUrl,
	// Taxonomies
	getTaxonomy,
	listTaxonomies,
	createTaxonomy,
	updateTaxonomy,
	deleteTaxonomy,
	restoreTaxonomy,
	// Terms
	getTerm,
	listTerms,
	getTermsHierarchy,
	suggestTerms,
	countTerms,
	createTerm,
	updateTerm,
	deleteTerm,
	restoreTerm,
	// Entry-Term Relations
	getTermsByEntry,
	getEntriesByTerm,
	setEntryTerms,
	addTermToEntry,
	removeTermFromEntry,
	createTermAndAddToEntry,
	// Media-Term Relations
	getTermsByMedia,
	getMediaByTerm,
	setMediaTerms,
	addTermToMedia,
	removeTermFromMedia,
	createTermAndAddToMedia,
	// Settings
	getSettings,
	updateSettings,
	resetSettings,
	// Namespaced exports for CmsAdmin component
	stats,
	settings,
	contentTypes,
	entries,
	bulk,
	trash,
	contentLock,
	versions,
	media,
	taxonomies,
} = defineAdminAPI(components.cms, {
	contentTypes: { changelogEntry, roadmapItem },
});
