import fs from "fs";
import path from "path";

interface InitOptions {
  force?: boolean;
}

const ADMIN_TEMPLATE = `/**
 * Admin API for CMS Admin UI
 *
 * This file exports Convex functions that the admin UI calls.
 * Generated by: npx convex-cms init
 *
 * @example Usage with embedded admin:
 * \`\`\`tsx
 * import { CmsAdmin } from "convex-cms-admin";
 *
 * function AdminPage() {
 *   return (
 *     <CmsAdmin
 *       convexUrl={import.meta.env.VITE_CONVEX_URL}
 *       auth={{
 *         getUser: () => yourAuth.getUser(),
 *         getUserRole: (id) => yourAuth.getRole(id),
 *       }}
 *     />
 *   );
 * }
 * \`\`\`
 */

import { defineAdminAPI } from "convex-cms";
import { components } from "./_generated/api";

export const {
  // Content Types
  listContentTypes,
  getContentType,
  createContentType,
  updateContentType,
  deleteContentType,

  // Entries
  listEntries,
  getEntry,
  createEntry,
  updateEntry,
  publishEntry,
  unpublishEntry,
  deleteEntry,
  duplicateEntry,
  scheduleEntry,
  cancelScheduledEntry,
  getScheduledEntries,

  // Media Assets
  listMediaAssets,
  getMediaAsset,
  createMediaAsset,
  updateMediaAsset,
  deleteMediaAsset,
  restoreMediaAsset,
  moveMediaAssets,

  // Media Folders
  listMediaFolders,
  getMediaFolder,
  getMediaFolderTree,
  createMediaFolder,
  updateMediaFolder,
  moveMediaFolder,
  deleteMediaFolder,
  restoreMediaFolder,

  // Upload
  generateUploadUrl,

  // Stats
  getDashboardStats,
} = defineAdminAPI(components.convexCms, {
  // Optional: Add auth callback to validate access
  // auth: async (ctx, operation) => {
  //   const identity = await ctx.auth.getUserIdentity();
  //   if (!identity) {
  //     throw new Error("Unauthorized: Please sign in");
  //   }
  //   // Optionally check operation.type for fine-grained access control
  //   return identity.subject;
  // },
});
`;

export async function initCommand(options: InitOptions): Promise<void> {
  const cwd = process.cwd();
  const convexDir = path.join(cwd, "convex");
  const adminPath = path.join(convexDir, "admin.ts");

  console.log("");
  console.log("  Convex CMS - Init");
  console.log("  -----------------");
  console.log("");

  // Check if convex/ directory exists
  if (!fs.existsSync(convexDir)) {
    console.error("  Error: No convex/ directory found.");
    console.error("");
    console.error("  Please run this command from a Convex project root,");
    console.error("  or initialize Convex first with: npx convex dev");
    process.exit(1);
  }

  // Check if admin.ts already exists
  if (fs.existsSync(adminPath) && !options.force) {
    console.error("  Error: convex/admin.ts already exists.");
    console.error("");
    console.error("  Use --force to overwrite the existing file.");
    process.exit(1);
  }

  // Write the admin.ts file
  try {
    fs.writeFileSync(adminPath, ADMIN_TEMPLATE);
    console.log("  Created convex/admin.ts");
  } catch (error) {
    console.error("  Error writing convex/admin.ts:", error);
    process.exit(1);
  }

  // Check if convex.config.ts mentions convexCms
  const configPath = path.join(convexDir, "convex.config.ts");
  let configHasComponent = false;

  if (fs.existsSync(configPath)) {
    const configContent = fs.readFileSync(configPath, "utf-8");
    configHasComponent = configContent.includes("convexCms");
  }

  console.log("");
  console.log("  Next steps:");
  console.log("");

  if (!configHasComponent) {
    console.log("  1. Add the CMS component to convex/convex.config.ts:");
    console.log("");
    console.log('     import convexCms from "convex-cms/convex.config";');
    console.log("");
    console.log("     const app = defineApp();");
    console.log("     app.use(convexCms);");
    console.log("     export default app;");
    console.log("");
    console.log("  2. Run Convex dev server:");
    console.log("     npx convex dev");
    console.log("");
    console.log("  3. Access admin (development):");
    console.log("     npx convex-cms admin");
  } else {
    console.log("  1. Run Convex dev server:");
    console.log("     npx convex dev");
    console.log("");
    console.log("  2. Access admin (development):");
    console.log("     npx convex-cms admin");
  }

  console.log("");
  console.log("  For production, embed the admin UI in your app:");
  console.log("  https://github.com/obkaro/convex-cms#embedding-admin-ui");
  console.log("");
}
