import { describe, it, expect } from "vitest";
import {
  parseLocale,
  formatLocale,
  getLocaleHierarchy,
  resolveFallbackChain,
  getFallbackChain,
  buildLocaleResolutionOptions,
  createFallbackConfig,
  validateFallbackConfig,
  mergeFallbackPresets,
  FALLBACK_PRESETS,
  DEFAULT_FALLBACK_CONFIG,
  type LocaleFallbackConfig,
} from "../../src/component/localeFallbackChain.js";

describe("Locale Fallback Chain", () => {
  // ===========================================================================
  // Locale Parsing Tests
  // ===========================================================================

  describe("parseLocale", () => {
    it("should parse simple language codes", () => {
      const result = parseLocale("en");
      expect(result).toEqual({ language: "en" });
    });

    it("should parse language with region", () => {
      const result = parseLocale("en-US");
      expect(result).toEqual({ language: "en", region: "US" });
    });

    it("should parse language with script", () => {
      const result = parseLocale("zh-Hans");
      expect(result).toEqual({ language: "zh", script: "Hans" });
    });

    it("should parse language with script and region", () => {
      const result = parseLocale("zh-Hans-CN");
      expect(result).toEqual({ language: "zh", script: "Hans", region: "CN" });
    });

    it("should return null for invalid locales", () => {
      expect(parseLocale("")).toBeNull();
      expect(parseLocale("invalid")).toBeNull();
      expect(parseLocale("en_US")).toBeNull(); // underscore instead of hyphen
      expect(parseLocale("EN-US")).toBeNull(); // uppercase language
    });

    it("should handle three-letter language codes", () => {
      const result = parseLocale("spa");
      expect(result).toEqual({ language: "spa" });
    });
  });

  describe("formatLocale", () => {
    it("should format language only", () => {
      expect(formatLocale({ language: "en" })).toBe("en");
    });

    it("should format language with region", () => {
      expect(formatLocale({ language: "en", region: "US" })).toBe("en-US");
    });

    it("should format language with script", () => {
      expect(formatLocale({ language: "zh", script: "Hans" })).toBe("zh-Hans");
    });

    it("should format language with script and region", () => {
      expect(formatLocale({ language: "zh", script: "Hans", region: "CN" })).toBe("zh-Hans-CN");
    });
  });

  describe("getLocaleHierarchy", () => {
    it("should return empty array for simple language codes", () => {
      expect(getLocaleHierarchy("en")).toEqual([]);
    });

    it("should return language for language-region locales", () => {
      expect(getLocaleHierarchy("en-US")).toEqual(["en"]);
      expect(getLocaleHierarchy("es-MX")).toEqual(["es"]);
    });

    it("should return language for language-script locales", () => {
      expect(getLocaleHierarchy("zh-Hans")).toEqual(["zh"]);
    });

    it("should return full hierarchy for language-script-region locales", () => {
      expect(getLocaleHierarchy("zh-Hans-CN")).toEqual(["zh-Hans", "zh"]);
    });

    it("should return empty array for invalid locales", () => {
      expect(getLocaleHierarchy("invalid")).toEqual([]);
    });
  });

  // ===========================================================================
  // Fallback Chain Resolution Tests
  // ===========================================================================

  describe("resolveFallbackChain", () => {
    const config: LocaleFallbackConfig = {
      defaultLocale: "en-US",
      fallbackChains: {
        "es-MX": ["es-ES"],
        "es-AR": ["es-ES"],
        "pt-BR": ["pt-PT", "en"],
      },
      autoGenerateFallbacks: true,
      supportedLocales: [],
    };

    it("should use explicit fallback chain when configured", () => {
      const result = resolveFallbackChain("es-MX", config);

      expect(result.requestedLocale).toBe("es-MX");
      expect(result.fallbackChain).toEqual(["es-ES", "en-US"]);
      expect(result.defaultLocale).toBe("en-US");
      expect(result.isAutoGenerated).toBe(false);
    });

    it("should auto-generate fallback chain when not explicitly configured", () => {
      const result = resolveFallbackChain("fr-CA", config);

      expect(result.requestedLocale).toBe("fr-CA");
      expect(result.fallbackChain).toEqual(["fr", "en-US"]);
      expect(result.isAutoGenerated).toBe(true);
    });

    it("should include default locale in chain", () => {
      const result = resolveFallbackChain("de-DE", config);

      expect(result.fallbackChain).toContain("en-US");
    });

    it("should not include the requested locale in the chain", () => {
      const result = resolveFallbackChain("en-US", config);

      expect(result.fallbackChain).not.toContain("en-US");
    });

    it("should deduplicate fallback chain", () => {
      const configWithDupes: LocaleFallbackConfig = {
        defaultLocale: "en",
        fallbackChains: {
          "es-MX": ["es-ES", "en", "es-ES"], // duplicate es-ES
        },
      };

      const result = resolveFallbackChain("es-MX", configWithDupes);
      expect(result.fallbackChain).toEqual(["es-ES", "en"]);
    });

    it("should respect supportedLocales filter", () => {
      const configWithSupported: LocaleFallbackConfig = {
        defaultLocale: "en",
        fallbackChains: {
          "es-MX": ["es-ES", "es", "en"],
        },
        supportedLocales: ["en", "es-ES"], // es is not supported
      };

      const result = resolveFallbackChain("es-MX", configWithSupported);
      expect(result.fallbackChain).toEqual(["es-ES", "en"]);
      expect(result.fallbackChain).not.toContain("es");
    });

    it("should use default config when none provided", () => {
      const result = resolveFallbackChain("fr-FR");

      expect(result.defaultLocale).toBe("en");
      expect(result.fallbackChain).toContain("en");
    });
  });

  describe("getFallbackChain", () => {
    it("should return simple array of fallback locales", () => {
      const config: LocaleFallbackConfig = {
        defaultLocale: "en",
        fallbackChains: {
          "es-MX": ["es-ES"],
        },
      };

      const chain = getFallbackChain("es-MX", config);
      expect(chain).toEqual(["es-ES", "en"]);
    });

    it("should work with default config", () => {
      const chain = getFallbackChain("en-US");
      expect(Array.isArray(chain)).toBe(true);
      expect(chain).toContain("en");
    });
  });

  describe("buildLocaleResolutionOptions", () => {
    it("should build LocaleResolutionOptions from config", () => {
      const config: LocaleFallbackConfig = {
        defaultLocale: "en-US",
        fallbackChains: {
          "es-MX": ["es-ES"],
        },
      };

      const options = buildLocaleResolutionOptions("es-MX", config);

      expect(options.locale).toBe("es-MX");
      expect(options.fallbackChain).toEqual(["es-ES", "en-US"]);
      expect(options.defaultLocale).toBe("en-US");
    });
  });

  // ===========================================================================
  // Configuration Utilities Tests
  // ===========================================================================

  describe("createFallbackConfig", () => {
    it("should create config with defaults", () => {
      const config = createFallbackConfig();

      expect(config.defaultLocale).toBe(DEFAULT_FALLBACK_CONFIG.defaultLocale);
      expect(config.fallbackChains).toEqual({});
      expect(config.autoGenerateFallbacks).toBe(true);
      expect(config.supportedLocales).toEqual([]);
    });

    it("should merge provided values with defaults", () => {
      const config = createFallbackConfig({
        defaultLocale: "en-US",
        fallbackChains: { "es-MX": ["es-ES"] },
      });

      expect(config.defaultLocale).toBe("en-US");
      expect(config.fallbackChains).toEqual({ "es-MX": ["es-ES"] });
      expect(config.autoGenerateFallbacks).toBe(true);
    });
  });

  describe("validateFallbackConfig", () => {
    it("should return no errors for valid config", () => {
      const config: LocaleFallbackConfig = {
        defaultLocale: "en-US",
        fallbackChains: {
          "es-MX": ["es-ES", "en-US"],
        },
        supportedLocales: ["en-US", "es-ES", "es-MX"],
      };

      const errors = validateFallbackConfig(config);
      expect(errors).toEqual([]);
    });

    it("should detect invalid default locale", () => {
      const config: LocaleFallbackConfig = {
        defaultLocale: "invalid!",
      };

      const errors = validateFallbackConfig(config);
      expect(errors).toContain("Invalid defaultLocale format: 'invalid!'");
    });

    it("should detect default locale not in supported locales", () => {
      const config: LocaleFallbackConfig = {
        defaultLocale: "en-US",
        supportedLocales: ["es-ES", "fr-FR"], // en-US not included
      };

      const errors = validateFallbackConfig(config);
      expect(errors).toContain("defaultLocale 'en-US' is not in supportedLocales");
    });

    it("should detect invalid locale in fallback chains", () => {
      const config: LocaleFallbackConfig = {
        defaultLocale: "en",
        fallbackChains: {
          "es-MX": ["invalid!"],
        },
      };

      const errors = validateFallbackConfig(config);
      expect(errors).toContain("Invalid fallback locale format for 'es-MX': 'invalid!'");
    });

    it("should detect self-reference in fallback chain", () => {
      const config: LocaleFallbackConfig = {
        defaultLocale: "en",
        fallbackChains: {
          "es-MX": ["es-MX", "en"], // self-reference
        },
      };

      const errors = validateFallbackConfig(config);
      expect(errors).toContain("Fallback chain for 'es-MX' contains self-reference");
    });

    it("should detect unsupported locale in fallback chain", () => {
      const config: LocaleFallbackConfig = {
        defaultLocale: "en",
        fallbackChains: {
          "es-MX": ["es-ES"],
        },
        supportedLocales: ["en", "es-MX"], // es-ES not supported
      };

      const errors = validateFallbackConfig(config);
      expect(errors).toContain("Fallback chain for 'es-MX' contains unsupported locale: 'es-ES'");
    });
  });

  // ===========================================================================
  // Preset Tests
  // ===========================================================================

  describe("FALLBACK_PRESETS", () => {
    it("should have Spanish preset", () => {
      expect(FALLBACK_PRESETS.spanish).toBeDefined();
      expect(FALLBACK_PRESETS.spanish["es-MX"]).toEqual(["es-ES", "en"]);
    });

    it("should have Portuguese preset", () => {
      expect(FALLBACK_PRESETS.portuguese).toBeDefined();
      expect(FALLBACK_PRESETS.portuguese["pt-BR"]).toEqual(["pt-PT", "en"]);
    });

    it("should have Chinese preset with script variants", () => {
      expect(FALLBACK_PRESETS.chinese).toBeDefined();
      expect(FALLBACK_PRESETS.chinese["zh-Hans-CN"]).toEqual(["zh-Hans", "zh", "en"]);
      expect(FALLBACK_PRESETS.chinese["zh-Hant-TW"]).toEqual(["zh-Hant", "zh", "en"]);
    });

    it("should have French preset", () => {
      expect(FALLBACK_PRESETS.french).toBeDefined();
      expect(FALLBACK_PRESETS.french["fr-CA"]).toEqual(["fr-FR", "en"]);
    });

    it("should have German preset", () => {
      expect(FALLBACK_PRESETS.german).toBeDefined();
      expect(FALLBACK_PRESETS.german["de-AT"]).toEqual(["de-DE", "en"]);
    });

    it("should have English preset", () => {
      expect(FALLBACK_PRESETS.english).toBeDefined();
      expect(FALLBACK_PRESETS.english["en-GB"]).toEqual(["en-US", "en"]);
    });
  });

  describe("mergeFallbackPresets", () => {
    it("should merge multiple presets", () => {
      const merged = mergeFallbackPresets(["spanish", "portuguese"]);

      // Spanish presets
      expect(merged["es-MX"]).toEqual(["es-ES", "en"]);
      expect(merged["es-AR"]).toEqual(["es-ES", "en"]);

      // Portuguese presets
      expect(merged["pt-BR"]).toEqual(["pt-PT", "en"]);
    });

    it("should return empty object for empty array", () => {
      const merged = mergeFallbackPresets([]);
      expect(merged).toEqual({});
    });

    it("should handle single preset", () => {
      const merged = mergeFallbackPresets(["french"]);
      expect(merged["fr-CA"]).toEqual(["fr-FR", "en"]);
      expect(merged["es-MX"]).toBeUndefined();
    });
  });

  // ===========================================================================
  // Integration Tests
  // ===========================================================================

  describe("Integration with locale resolution", () => {
    it("should work end-to-end: config -> resolution -> options", () => {
      // Step 1: Create a configuration
      const config = createFallbackConfig({
        defaultLocale: "en-US",
        fallbackChains: {
          "es-MX": ["es-ES"],
          "pt-BR": ["pt-PT"],
        },
        supportedLocales: ["en-US", "es-MX", "es-ES", "pt-BR", "pt-PT"],
      });

      // Step 2: Validate the configuration
      const errors = validateFallbackConfig(config);
      expect(errors).toEqual([]);

      // Step 3: Resolve fallback chain
      const resolved = resolveFallbackChain("es-MX", config);
      expect(resolved.fallbackChain).toEqual(["es-ES", "en-US"]);

      // Step 4: Build locale resolution options
      const options = buildLocaleResolutionOptions("es-MX", config);
      expect(options.locale).toBe("es-MX");
      expect(options.fallbackChain).toEqual(["es-ES", "en-US"]);
      expect(options.defaultLocale).toBe("en-US");
    });

    it("should handle complex Chinese locale hierarchy", () => {
      // Build config with Chinese presets (converting readonly arrays)
      const chineseChains: Record<string, string[]> = {};
      for (const [locale, chain] of Object.entries(FALLBACK_PRESETS.chinese)) {
        chineseChains[locale] = [...chain];
      }

      const config: LocaleFallbackConfig = {
        defaultLocale: "en",
        fallbackChains: chineseChains,
      };

      // Test Simplified Chinese (China)
      const simplified = resolveFallbackChain("zh-Hans-CN", config);
      expect(simplified.fallbackChain).toEqual(["zh-Hans", "zh", "en"]);

      // Test Traditional Chinese (Taiwan)
      const traditional = resolveFallbackChain("zh-Hant-TW", config);
      expect(traditional.fallbackChain).toEqual(["zh-Hant", "zh", "en"]);
    });

    it("should auto-generate reasonable fallbacks for unknown locales", () => {
      const config: LocaleFallbackConfig = {
        defaultLocale: "en",
        autoGenerateFallbacks: true,
      };

      // New locale not in any preset
      const result = resolveFallbackChain("ja-JP", config);

      expect(result.isAutoGenerated).toBe(true);
      expect(result.fallbackChain).toContain("ja"); // Base language
      expect(result.fallbackChain).toContain("en"); // Default
    });
  });
});
